### ISSUE TITLE
Analog Villain3DS

### ISSUE THREAD

**Issue by ghost** [luigoalma/ctrcdnfetch#5]
There is a proposal to make an analogue Villain3DS . The database will be original tickets from different consoles of the world and will be replenished.There are 4 tickets in my database.
![Безымянный](https://user-images.githubusercontent.com/35849884/59149095-e1e1d500-8a19-11e9-9b9d-d9a39f392775.jpg)

**Comment by luigoalma** [comment]
hm? I might have not understood, make an "analogue Villain3DS"?
What are you trying to issue here?

**Comment by luigoalma** [comment]
I got my answer on what "Villain3DS" is.
That's a no. If you're issuing this here, you must clearly have not read the [Notice](https://github.com/luigoalma/ctrcdnfetch/blob/db111fd8fdbac94399ff174d5f2190dafe008a48/README.md#notice) on [README.md](https://github.com/luigoalma/ctrcdnfetch/blob/db111fd8fdbac94399ff174d5f2190dafe008a48/README.md).
A loading a local database, like your own private ticket.db or a custom one with __your tickets alone__ would be one thing. Now what you're asking me is to have it use a database that `will be original tickets from different consoles of the world`, that's sounds like very explicitly piracy, because you are not getting tickets you bought yourself from the eshop, and I'm guessing you want an online kind of service like the title key databases that existed, but where people share out full tickets.
If you want one, better off making it yourself or finding someone else.
And read the [README.md](https://github.com/luigoalma/ctrcdnfetch/blob/db111fd8fdbac94399ff174d5f2190dafe008a48/README.md). I got a warning there about ticket's console unique data. Think twice.
